name: PLLController
type: group
children:
- name: output0_select
  path: _output0_select_parameter.value
  type: list
  limits:
    In 0: 0
    In 1: 1
    PLL 0: 2
    PLL 1: 3
    PLL 2: 4
    PLL 3: 5
    Sum 0: 6
    Sum 1: 7
- name: output1_select
  path: _output1_select_parameter.value
  type: list
  limits:
    In 0: 0
    In 1: 1
    PLL 0: 2
    PLL 1: 3
    PLL 2: 4
    PLL 3: 5
    Sum 0: 6
    Sum 1: 7
- name: constant0
  path: _constant0_parameter.value
  type: float
  limits: [-1, 1]
  units: V
  siPrefix: true
- name: constant1
  path: _constant1_parameter.value
  type: float
  limits: [-1, 1]
  units: V
  siPrefix: true
- name: sum0
  type: group
  children:
  - name: divide_by
    path: _divide_by_parameter.value
    type: int
    limits: [1, 8]
  - name: In0
    path: _add0_parameter.value
    type: bool
  - name: In1
    path: _add1_parameter.value
    type: bool
  - name: PLL0
    path: _add2_parameter.value
    type: bool
  - name: PLL1
    path: _add3_parameter.value
    type: bool
  - name: PLL2
    path: _add4_parameter.value
    type: bool
  - name: PLL3
    path: _add5_parameter.value
    type: bool
  - name: constant0
    path: _add6_parameter.value
    type: bool
  - name: constant1
    path: _add7_parameter.value
    type: bool
- name: sum1
  type: group
  children:
  - name: divide_by
    path: _divide_by_parameter.value
    type: int
    limits: [1, 8]
  - name: In0
    path: _add0_parameter.value
    type: bool
  - name: In1
    path: _add1_parameter.value
    type: bool
  - name: PLL0
    path: _add2_parameter.value
    type: bool
  - name: PLL1
    path: _add3_parameter.value
    type: bool
  - name: PLL2
    path: _add4_parameter.value
    type: bool
  - name: PLL3
    path: _add5_parameter.value
    type: bool
  - name: constant0
    path: _add6_parameter.value
    type: bool
  - name: constant1
    path: _add7_parameter.value
    type: bool
- name: pll0
  type: group
  children:
  - name: input_select
    path: _input_select_parameter.value
    type: list
    limits:
      In 0: 0
      In 1: 1
  - name: second_harmonic
    path: _pll_second_harmonic_parameter_module.second_harmonic
    type: bool
  - name: frequency
    path: _pll_second_harmonic_parameter_module.frequency
    type: float
    limits: [1, 7.8125e6]
    units: Hz
    siPrefix: true
  - name: a
    path: _amplitude_phase_module.a
    type: float
    limits: [0, 1]
    units: V
    siPrefix: true
  - name: phi
    path: _amplitude_phase_module.phi
    type: float
    limits: [-180, 180]
    units: deg
  - name: demodulator_bandwidth
    path: _pll_second_harmonic_parameter_module.demodulator_bandwidth
    type: float
    limits: [0, 114e3]
    units: Hz
    siPrefix: true
  - name: order
    path: _order_parameter.value
    type: int
    limits: [1, 8]
  - name: pid_enable
    path: _pid_enable_parameter.value
    type: bool
  - name: pid_bandwidth
    path: _pid_bandwidth_parameter.value
    type: float
    limits: [0, 15.625e6]
    units: Hz
    siPrefix: true
  - name: kp
    path: _kp_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: ki
    path: _ki_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: output_select
    path: _output_select_parameter.value
    type: list
    limits:
      PLL out: 0
      demod x: 1
      demod y: 2
      demod r: 3
      demod theta: 4
      constant: 5
  - name: gain
    path: _gain_module.gain
    type: float
    limits: [-1e6, 1e6]
  - name: constant
    path: _constant_parameter.value
    type: float
    limits: [-1, 1]
    units: V
    siPrefix: true
- name: pll1
  type: group
  children:
  - name: input_select
    path: _input_select_parameter.value
    type: list
    limits:
      In 0: 0
      In 1: 1
  - name: second_harmonic
    path: _pll_second_harmonic_parameter_module.second_harmonic
    type: bool
  - name: frequency
    path: _pll_second_harmonic_parameter_module.frequency
    type: float
    limits: [1, 7.8125e6]
    units: Hz
    siPrefix: true
  - name: a
    path: _amplitude_phase_module.a
    type: float
    limits: [0, 1]
    units: V
    siPrefix: true
  - name: phi
    path: _amplitude_phase_module.phi
    type: float
    limits: [-180, 180]
    units: deg
  - name: demodulator_bandwidth
    path: _pll_second_harmonic_parameter_module.demodulator_bandwidth
    type: float
    limits: [0, 114e3]
    units: Hz
    siPrefix: true
  - name: order
    path: _order_parameter.value
    type: int
    limits: [1, 8]
  - name: pid_enable
    path: _pid_enable_parameter.value
    type: bool
  - name: pid_bandwidth
    path: _pid_bandwidth_parameter.value
    type: float
    limits: [0, 15.625e6]
    units: Hz
    siPrefix: true
  - name: kp
    path: _kp_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: ki
    path: _ki_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: output_select
    path: _output_select_parameter.value
    type: list
    limits:
      PLL out: 0
      demod x: 1
      demod y: 2
      demod r: 3
      demod theta: 4
      constant: 5
  - name: gain
    path: _gain_module.gain
    type: float
    limits: [-1e6, 1e6]
  - name: constant
    path: _constant_parameter.value
    type: float
    limits: [-1, 1]
    units: V
    siPrefix: true
- name: pll2
  type: group
  children:
  - name: input_select
    path: _input_select_parameter.value
    type: list
    limits:
      In 0: 0
      In 1: 1
  - name: second_harmonic
    path: _pll_second_harmonic_parameter_module.second_harmonic
    type: bool
  - name: frequency
    path: _pll_second_harmonic_parameter_module.frequency
    type: float
    limits: [1, 7.8125e6]
    units: Hz
    siPrefix: true
  - name: a
    path: _amplitude_phase_module.a
    type: float
    limits: [0, 1]
    units: V
    siPrefix: true
  - name: phi
    path: _amplitude_phase_module.phi
    type: float
    limits: [-180, 180]
    units: deg
  - name: demodulator_bandwidth
    path: _pll_second_harmonic_parameter_module.demodulator_bandwidth
    type: float
    limits: [0, 114e3]
    units: Hz
    siPrefix: true
  - name: order
    path: _order_parameter.value
    type: int
    limits: [1, 8]
  - name: pid_enable
    path: _pid_enable_parameter.value
    type: bool
  - name: pid_bandwidth
    path: _pid_bandwidth_parameter.value
    type: float
    limits: [0, 15.625e6]
    units: Hz
    siPrefix: true
  - name: kp
    path: _kp_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: ki
    path: _ki_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: output_select
    path: _output_select_parameter.value
    type: list
    limits:
      PLL out: 0
      demod x: 1
      demod y: 2
      demod r: 3
      demod theta: 4
      constant: 5
  - name: gain
    path: _gain_module.gain
    type: float
    limits: [-1e6, 1e6]
  - name: constant
    path: _constant_parameter.value
    type: float
    limits: [-1, 1]
    units: V
    siPrefix: true
- name: pll3
  type: group
  children:
  - name: input_select
    path: _input_select_parameter.value
    type: list
    limits:
      In 0: 0
      In 1: 1
  - name: second_harmonic
    path: _pll_second_harmonic_parameter_module.second_harmonic
    type: bool
  - name: frequency
    path: _pll_second_harmonic_parameter_module.frequency
    type: float
    limits: [1, 7.8125e6]
    units: Hz
    siPrefix: true
  - name: a
    path: _amplitude_phase_module.a
    type: float
    limits: [0, 1]
    units: V
    siPrefix: true
  - name: phi
    path: _amplitude_phase_module.phi
    type: float
    limits: [-180, 180]
    units: deg
  - name: demodulator_bandwidth
    path: _pll_second_harmonic_parameter_module.demodulator_bandwidth
    type: float
    limits: [0, 114e3]
    units: Hz
    siPrefix: true
  - name: order
    path: _order_parameter.value
    type: int
    limits: [1, 8]
  - name: pid_enable
    path: _pid_enable_parameter.value
    type: bool
  - name: pid_bandwidth
    path: _pid_bandwidth_parameter.value
    type: float
    limits: [0, 15.625e6]
    units: Hz
    siPrefix: true
  - name: kp
    path: _kp_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: ki
    path: _ki_parameter.value
    type: float
    limits: [-32768, 32767]
  - name: output_select
    path: _output_select_parameter.value
    type: list
    limits:
      PLL out: 0
      demod x: 1
      demod y: 2
      demod r: 3
      demod theta: 4
      constant: 5
  - name: gain
    path: _gain_module.gain
    type: float
    limits: [-1e6, 1e6]
  - name: constant
    path: _constant_parameter.value
    type: float
    limits: [-1, 1]
    units: V
    siPrefix: true
